package site.zhangsun.generator.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import site.zhangsun.generator.pojo.entity.GeneratorEntity;
import site.zhangsun.generator.pojo.entity.GeneratorEntityExample;
import site.zhangsun.generator.pojo.entity.GeneratorEntityKey;

public interface GeneratorEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    long countByExample(GeneratorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int deleteByExample(GeneratorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int deleteByPrimaryKey(GeneratorEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int insert(GeneratorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int insertSelective(GeneratorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    List<GeneratorEntity> selectByExample(GeneratorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    GeneratorEntity selectByPrimaryKey(GeneratorEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int updateByExampleSelective(@Param("record") GeneratorEntity record, @Param("example") GeneratorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int updateByExample(@Param("record") GeneratorEntity record, @Param("example") GeneratorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int updateByPrimaryKeySelective(GeneratorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator
     *
     * @mbg.generated 2019-11-03 08:24:13
     */
    int updateByPrimaryKey(GeneratorEntity record);
}