package site.zhangsun.generator.pojo.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table generator
 * @author zhangsunjiankun
 * @date 2019-11-03 12:43:00
 * @since 1.0.0-SNAPSHOT

 *
 * @mbg.generated do_not_delete_during_merge Sun Nov 03 12:43:00 CST 2019
 */
public class GeneratorEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.id
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.id
     *
     * @return the value of generator.id
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.id
     *
     * @param id the value for generator.id
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}