package site.zhangsun.generator.pojo.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table generator
 * @author zhangsunjiankun
 * @date 2019-11-03 12:43:00
 * @since 1.0.0-SNAPSHOT

 *
 * @mbg.generated do_not_delete_during_merge Sun Nov 03 12:43:00 CST 2019
 */
public class GeneratorEntity extends GeneratorEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.name
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.code
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator.description
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.name
     *
     * @return the value of generator.name
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.name
     *
     * @param name the value for generator.name
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.code
     *
     * @return the value of generator.code
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.code
     *
     * @param code the value for generator.code
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator.description
     *
     * @return the value of generator.description
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator.description
     *
     * @param description the value for generator.description
     *
     * @mbg.generated Sun Nov 03 12:43:00 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}